### ISSUE TITLE
[REQ] building VM

### ISSUE THREAD

**Issue by MarcoRavich** [hashbang/aosp-build#34]
Hi there, it would be great to setup a device-agnostic VM based on your build system to "automatically" compile - feeding it with right device trees needed, of course - AOSP (and, why not, derived customs).

Check out this cool @mfn003 colab:
https://github.com/viam1-dev/colab_lineage_build

Hope that inspires !

**Comment by ypid** [comment]
The link is dead. Supporting cloud providers and so on has been done before and is still partly in the code base (and bloated it a bit). We use Docker as abstraction. I see setting up a VM as out of scope for this project.

As for the device tree automation, not sure if we need that. I am more looking into the https://github.com/GrapheneOS/adevtool direction for that.

**Comment by MarcoRavich** [comment]
Hi there,
you're right, sorry, but it *was* active in Aug 2022... here's a working alternative: https://github.com/T110-android/colab_build

Thanks for pointing us to that Graphene's resource then, it's extremely interesting.

We believe that an "automated build service" (wich could include **adevtool** too, of course) could be a great "boosting factor" for any custom ROM.

Something like this would allow - as far as possible - end users to build (unofficial, of course) customs themselves by "just" linking a stock ROM.

Hope that inspires.
