### ISSUE TITLE
Switch to Debian baseimage

### ISSUE THREAD

**Issue by ypid** [hashbang/aosp-build#4]
Is there an interest from others to switch the Docker base image to a Debian one (Buster)? I have more trust in Debian than Ubuntu. Also, for me this would simplify the usage of this project because I build the Docker base image and of course this image myself so I do not have to put any trust into Docker Hub and can review all of the build scripts myself. Ref: https://github.com/ypid/docker-makefile (easy to review, no fancy stuff).

**Comment by lrvick** [comment]
The only reason I chose the ubuntu version I did is that was the only version the toolchain officially supports. That said if we switch to the debian toolchain too per your other ticket, this would be a non issue. Should tackle these in tandem imo. If it works, I am down.

**Comment by ypid** [comment]
Awesome, than we are on the same page :) Just for others reading this, the other issue we are referring to is #10.

I have also waited with doing work in those areas (plus reproducible build testing) because I think they can really benefit from having more powerful build servers available. And as I don’t like clouds, I will need to bring those machines online myself. Working on that.

**Comment by ypid** [comment]
Done and able to build GrapheneOS successfully as userbuild. If someone wants this earlier, ping me and I can open a PR. Otherwise, I will push it later when I addressed https://github.com/hashbang/os/issues/45.
